Made more portable, added responses.
1- Config and resource paths now store in KDE's config (rc) folder
2- Every variable has a UI prompt, and saves settings in config
3- pushlink now triggers a 'passive popup' on completion
detailing the result or error
4- Add pb-devices - In future will use to select target push device(s)

diff --git a/scripts/pushlink b/scripts/pushlink
--- a/scripts/pushlink
+++ b/scripts/pushlink
@@ -1,26 +1,50 @@
 #!/bin/bash
-apikey="$(cat "/home/ethan/.kde/share/apps/kpushbullet/APIkey")"
+
+readconf () {
+iconfile=$(kreadconfig --file "kpushbulletrc" --group "General" --key "Icon")
+resourcedir=$(kreadconfig --file "kpushbulletrc" --group "General" --key "Resource Directory")
+apikey=$(kreadconfig --file "kpushbulletrc" --group "User Data" --key "APIKey")
+recentrss=$(kreadconfig --file "kpushbulletrc" --group "RSS Generator" --key "RSS Output File")
+rssheaderrs=$(kreadconfig --file "kpushbulletrc" --group "RSS Generator" --key "RSS Header Resource")
+rssfooterrs=$(kreadconfig --file "kpushbulletrc" --group "RSS Generator" --key "RSS Footer Resource")
+}
+locate_resource_dir () {
+(kdialog --caption "KPushBullet" --getexistingdirectory "$HOME" --title "Locate the resources directory!") | (kwriteconfig --file "kpushbulletrc" --group "General" --key "Resource Directory" $(cat -))
+(kwriteconfig --file "kpushbulletrc" --group "General" --key "Icon" "$resourcedir/icon.png")
+(kwriteconfig --file "kpushbulletrc" --group "RSS Generator" --key "RSS Header Resource" "$resourcedir/rssHeader")
+(kwriteconfig --file "kpushbulletrc" --group "RSS Generator" --key "RSS Footer Resource" "$resourcedir/rssFooter")
+readconf
+}
+
+readconf
+if [ ! -e "$resourcedir" ]
+  then
+  locate_resource_dir
+  readconf
+fi
+if [ -z $apikey ]
+    then 
+    # APIkey is undefined, so prompt the user for it
+    inputdesc="Please iput your PushBullet API key. The key is stored locally for convenience so you don't have to enter it every time you fetch your pushes. You have the option to opt-out of this convenience in the next step."
+    inputtitle="KPushBullet - Enter Your API Key."
+    
+    apikey="$(kdialog --icon "$iconfile" --caption "KPushBullet" --title "Setup" --password "$inputdesc" "")"
+    kdialog --yesno "Would you like to save the key for later?"; if [[ "$?" == 0 ]]; then (kwriteconfig --file "kpushbulletrc" --group "User Data" --key "APIKey" $apikey);readconf; fi
+fi
 #(curl https://api.pushbullet.com/v2/devices -u $apikey:) > 
 #| jq '[.devices] | .[0]') | awk -F ":" '/\:/ { print $0 }'
-vir_path="$(echo $0)"
-real_kpb_root="$(ls -l "$vir_path" | awk -F "-> " '{print $2}'|awk -F "\/scripts\/" '{print $1}')"
+#vir_path="$(echo $0)"
+#real_kpb_root="$(ls -l "$vir_path" | awk -F "-> " '{print $2}'|awk -F "\/scripts\/" '{print $1}')"
 
 inputdesc="The page title will be generated for you. "
 inputtitle="KPushBullet - Push New Link"
-#inputw="400"
-#inputh="300"
-#trigger_link_d () {
-#linkcontent="$(kdialog --inputbox "$inputdesc" "" --title "$inputtitle")"
-#linklength="${#linkcontent}"
-#}
 
-#trigger_link_d
-linkcontent="$(kdialog --icon "/home/ethan/.kde/share/apps/kpushbullet/icon.png" --inputbox "$inputdesc" "" --title "$inputtitle")"
+linkcontent="$(kdialog --icon "$iconfile" --inputbox "$inputdesc" "" --title "$inputtitle")"
 linklength="${#linkcontent}"
 if [[ "$linklength" > 0 ]]
 then
 autolinkname="$(curl -s -N "$linkcontent" | awk -F "<|>" '$2=="title" { print $3 }')"
-curl https://api.pushbullet.com/v2/pushes -u $apikey: -d type="link" -d title="$autolinkname" -d url="$linkcontent" -X POST
+(curl https://api.pushbullet.com/v2/pushes -u $apikey: -s -d type="link" -d title="$autolinkname" -d url="$linkcontent" -X POST --stderr -) | jq -r '.| if .error then .error | "<<ERROR>>Error.......\(.type)","<<ERROR>>\(.message)" else "Success:", .title, .url end'|sed -e 's/\(^<<ERROR>>.*\)/\U\1/;s/^<<ERROR>>//g'|(kdialog --icon "$iconfile" --passivepopup "$(cat -)" 20)
 else
 echo "${#linkcontent}"
 fi
